### ISSUE TITLE
What's the purpose of this project?

### ISSUE THREAD

**Issue by ramsey-coding** [huggingface/llm-ls#32]
Would love to know what problem this project wants to tackle. Happy to help as well!

**Comment by McPatate** [comment]
Hello @ramsey-coding, the goal of llm-ls is to provide a common platform for extensions to be build on. The idea is to provide the heavy lifting to interact with LLMs so that extension code can be as lightweight as possible.
My todo list might help you understand what I'm trying to accomplish:
```md
# Language server

- [ ] suffix percent of context window
- [ ] add context window total fill percent
- [ ] prompt telemetry
- [ ] oltp traces
- [ ] multi file support
- [ ] support for ollama
- [ ] support for llama.cpp
- [ ] filter bad suggestions (repetitive, same as below, etc)

## Additional commands

- [ ] refactor selected code block
- [ ] chat features
  - [ ] explain what this bit of code does

# VsCode

- [ ] status bar
- [ ] client side caching
  - match on beginning of string and line number?

# llm.nvim

# JetBrains

```

**Comment by erkkimon** [comment]
This was a great question because I couldn't figure out the exact role of this project either. Of course I understood that it acts as server interface or something for LLM but exact role definition was a mystery to me in the beginning. Can it be considered as an interface or abstraction layer between programming plugin and LLM endpoint?

**Comment by McPatate** [comment]
It's a sophisticated prompt builder 😄

**Comment by McPatate** [comment]
I've added some more info in the README, let me know if it's clear enough (feel free to open a PR / issue if not)
