### ISSUE TITLE
In Windows, it will cause bug sometimes.

### ISSUE THREAD

**Issue by mikeshi80** [huggingface/llm-ls#45]
https://github.com/huggingface/llm-ls/blob/f58085b8127dc09ae09645e04019a668a85e4976/crates/llm-ls/src/main.rs#L795

`Instant::now()` maybe return a value smaller than `MAX_WARNING_REPEAT` (3600s) in my Win11, and it will cause the `checked_sub` return None, that make program show error message "instant to be in bounds" and exit exceptionally.

I think it could be the reason:  https://doc.rust-lang.org/std/time/struct.Instant.html#underlying-system-calls

Windows use `QueryPerformanceCounter` as underlying system call.

My OS is Win11 Home Edition, 23H2 version.

**Comment by mikeshi80** [comment]
Maybe `std::time::SystemTime::now` is the right option, not `std::time::Instant::now`

**Comment by mikeshi80** [comment]
Does the author rarely reboot the computer?

**Comment by zhangwenhao666** [comment]
I also encountered the same problem on the Windows system. Later I checked GPT and he replied that it was possible that the MAX_WARNING_REPEAT setting was too large, so I changed const MAX_WARNING_REPEAT: Duration = Duration::from_secs(3_600); to const MAX_WARNING_REPEAT: Duration = Duration::from_secs(3_60);This problem is solved. I don’t know if there are any other problems with this solution.

**Comment by Ovich** [comment]
`Instant::now()` on Windows system does indeed return timestamp smaller than `MAX_WARNING_REPEAT` and throws an error, in some cases. As highlighted by @mikeshi80. 

The approach proposed by @mikeshi80 seem to work fine in my setup. It passes unit tests and its in working condition on my windows and mac.  Next step would be to run the test and release workflows. 

@McPatate Any ways to contribute to fixing this issue?
